### ISSUE TITLE
Player power bar moves to the left rather than emptying

### ISSUE THREAD

**Issue by Ivaria** [Rainrider/oUF_Rain#7]
I really love oUF_Rain.  I used oUF_Cael for years but he disappeared a few years back and the Caelian stuff went out of date.

However, as of pre-patch I grabbed your legion branch but the player powerbar gets offset to the left when emptying.  Target and focus power bars display properly when emptying.

See screenshot here for illustration.

![ouf_rain_broken_powerbar](https://cloud.githubusercontent.com/assets/13824152/17497978/5d751b58-5d79-11e6-911d-ea47784e023c.png)

**Comment by Rainrider** [comment]
oUF_Rain is currently more a mess than an addon. I haven't run into your issue on beta though. Where did you get oUF from?

**Comment by Ivaria** [comment]
oUF_Rain is the best clone of Caelian I have found that is still supported though!

Hmm that is a good question hah.  I think I found a fork on Github someone linked to from a WoWinterface forum thread.

Do you have a specific fork I should grab?

**Comment by Rainrider** [comment]
The version of oUF I use locally is quite dirty and way out of sync with the git repo. Maybe see what p3lim uses and try that one. I'll take a look when I get home later this evening.

**Comment by Rainrider** [comment]
Sorry, I can't reproduce that. I used a fresh copy of https://github.com/p3lim-wow/oUF. Could you verify my results with this version of oUF?

There are other issues of course, I'll try to get those fixed

**Comment by Ivaria** [comment]
Awesome, grabbing p3lim's latest fixed the issue.  Thanks and really love oUF_Rain.  Please keep supporting it!
